import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/client";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout for the application that wraps pages with global providers and base HTML structure.
 *
 * Renders the HTML root with lang="en" and a body that applies the Inter font and antialiasing, while
 * wrapping the entire tree with TRPCReactProvider so TRPC client context is available to descendants.
 *
 * @param children - The page content to be rendered inside the `<body>`.
 * @returns A React element representing the application root layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
          >
         {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
